### ISSUE TITLE
Write a blog post on "what is Krypton Chicken?".

### ISSUE THREAD

**Issue by smsunarto** [KryptonChicken/kryptonchicken.github.io#4]
Pretty straight forward, someone need to start creating content :)

**Comment by tommyip** [comment]
I uploaded a post on how we get the name, do you want to write a blog on what is Krypton Chicken?

**Comment by utkarsh-dixit** [comment]
#6 I guess this is a duplicate issue. Should we close this issue?

**Comment by tommyip** [comment]
Changing the title

**Comment by ghost** [comment]
@tommyip I would love to do it, assign it to me!

**Comment by ghost** [comment]
Sorry guys, I messed up..I am actually new to GitHub! I have already committed with the blog post and made some changes in other files too!

**Comment by tommyip** [comment]
No worries! Github can be intimating at first. The commits seems to be mixed up, can you make sure you have the right commits in the right PR? You can ask me if you are unsure.

**Comment by ghost** [comment]
Sorry, I dont know how to do so! Can you help me with this?

**Comment by tommyip** [comment]
No problem, lets chat in Telegram so the Github bot don't spam the chat.

**Comment by tommyip** [comment]
Any update on this?

**Comment by Yureien** [comment]
Can we replan for it @smsunarto
