### ISSUE TITLE
Add the "Play to" app to Projects

### ISSUE THREAD

**Issue by IlyaBizyaev** [KryptonChicken/kryptonchicken.github.io#7]
The idea is to write a user-friendly cross-platform "Play to" app (probably a DLNA server) with a decent GUI.
 Any ideas and comments are appreciated.

**Comment by tommyip** [comment]
What do you mean by "Play to"?

**Comment by IlyaBizyaev** [comment]
I mean a streaming application, visually as simple as Windows Explorer's "Play to" command in file context menu.
Apart from making a GUI, we could add this command to Dolphin's and Nautilus's menus.

**Comment by feelfreelinux** [comment]
Ok! I have an idea about protocol of it, can write basic library in c:

- Client connects to server, sends 2 bytes: Version of protocol, and Content type(Image, text, etc)
- Server responses with one byte code - Does it support this version and content type
- If response is valid, client starts sending data
- When all of data is send, client sends end message.
- Server responds, closes connection.

Thats basic implementation of this, then we need to make guis, etc.

**Comment by feelfreelinux** [comment]
Ok, forget the protocol, we want to implement DLnA/UPnP DMC. Language - propably C++.

**Comment by IlyaBizyaev** [comment]
Added.
Closing.
