### ISSUE TITLE
NEWCOMERS: Which trip are you on?

### ISSUE THREAD

**Issue by tommyip** [KryptonChicken/kryptonchicken.github.io#9]
If your name isn't on the trip list yet, can you tell me which trip (a/b) are you on so I can add to it.

**Comment by dkarakay** [comment]
@tommyip  Do you know anything about "BRL-CAD" Google Prize Winners? They aren't in the readme list. I don't know their trip(a/b) but just realized their absence.

**Comment by tommyip** [comment]
Everyone onboard!
